### ISSUE TITLE
Running scorebot

### ISSUE THREAD

**Issue by fmrosa** [dichotomy/scorebot#23]
Hi, 

There is any document explaining how to run scorebot? I was able to install it but can't create a ctf game since i don't know the procedure. Any doc explaining how to execute it? 

Thx

**Comment by fmrosa** [comment]
scorebot-setup.sh mentions about a doc at /docs/index.html containing instructions but the file isn't there ... can you please explain how to start the service and configure a ctf game?

**Comment by AnarKyx01** [comment]
Sorry, this has been added.  NOTE they are a work in progress, and more will be added shortly.  Please leave a comment with any questions/issues.
